### ISSUE TITLE
Hover color of the submenu in sidebar

### ISSUE THREAD

**Issue by minoic** [codedthemes/berry-free-vuetify-vuejs-admin-template#6]
The gray color only appears and disappears immediately after the mouse is moved away from the button.

Mouse on "Social Profile":

![image](https://github.com/codedthemes/berry-free-vuetify-vuejs-admin-template/assets/55825043/0578dd9e-2fa7-4973-968f-1b5d4b9c7edd)

Mouse leaving "Social Profile":

![image](https://github.com/codedthemes/berry-free-vuetify-vuejs-admin-template/assets/55825043/6434bee5-5628-491a-9077-14349950095e)

**Comment by phoenixcoded20** [comment]
This has been fixed in pro version since bug only exist in pro. Please download again.
